/**
 * Query history and snippet types
 *
 * These types mirror the Rust models for query execution history
 * and saved query snippets, enabling type-safe communication
 * between frontend and backend.
 */

/**
 * Query history record
 *
 * Represents a single executed query with metadata about the execution.
 */
export interface QueryHistory {
  /** Unique identifier (UUID) */
  id: string;

  /** Connection ID where query was executed */
  connectionId: string;

  /** Human-readable connection name */
  connectionName: string;

  /** Database name where query was executed */
  database: string;

  /** The SQL query text */
  query: string;

  /** ISO 8601 timestamp (e.g., "2025-11-19T12:34:56.789Z") */
  executedAt: string;

  /** Query execution time in milliseconds */
  executionTimeMs?: number;

  /** Number of rows returned or affected */
  rowCount?: number;

  /** Whether query executed successfully */
  success: boolean;

  /** Error message if query failed */
  errorMessage?: string;
}

/**
 * Saved query snippet
 *
 * Represents a user-saved SQL query snippet for quick access and reuse.
 */
export interface QuerySnippet {
  /** Unique identifier (UUID) */
  id: string;

  /** User-provided name */
  name: string;

  /** Optional description */
  description?: string;

  /** The SQL query text */
  query: string;

  /** Optional tags for categorization */
  tags?: string[];

  /** ISO 8601 timestamp of creation */
  createdAt: string;

  /** ISO 8601 timestamp of last update */
  updatedAt: string;
}

/**
 * Create a new query history record
 */
export function createQueryHistory(
  connectionId: string,
  connectionName: string,
  database: string,
  query: string,
  success: boolean,
  executionTimeMs?: number,
  rowCount?: number,
  errorMessage?: string
): QueryHistory {
  return {
    id: '', // Will be generated by backend
    connectionId,
    connectionName,
    database,
    query,
    executedAt: new Date().toISOString(),
    executionTimeMs,
    rowCount,
    success,
    errorMessage,
  };
}

/**
 * Create a new query snippet
 */
export function createQuerySnippet(
  name: string,
  query: string,
  description?: string,
  tags?: string[]
): Omit<QuerySnippet, 'id' | 'createdAt' | 'updatedAt'> {
  return {
    name,
    query,
    description,
    tags,
  };
}
