/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ConnectedRouteRouteImport } from './routes/_connected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectedVisualQueryRouteImport } from './routes/_connected/visual-query'
import { Route as ConnectedQueryRouteImport } from './routes/_connected/query'
import { Route as ConnectedActivityRouteImport } from './routes/_connected/activity'
import { Route as ConnectedErDiagramSchemaRouteImport } from './routes/_connected/er-diagram.$schema'
import { Route as ConnectedTableSchemaTableNameRouteRouteImport } from './routes/_connected/table.$schema.$tableName/route'
import { Route as ConnectedTableSchemaTableNameIndexRouteImport } from './routes/_connected/table.$schema.$tableName/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectedRouteRoute = ConnectedRouteRouteImport.update({
  id: '/_connected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectedVisualQueryRoute = ConnectedVisualQueryRouteImport.update({
  id: '/visual-query',
  path: '/visual-query',
  getParentRoute: () => ConnectedRouteRoute,
} as any)
const ConnectedQueryRoute = ConnectedQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => ConnectedRouteRoute,
} as any)
const ConnectedActivityRoute = ConnectedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ConnectedRouteRoute,
} as any)
const ConnectedErDiagramSchemaRoute =
  ConnectedErDiagramSchemaRouteImport.update({
    id: '/er-diagram/$schema',
    path: '/er-diagram/$schema',
    getParentRoute: () => ConnectedRouteRoute,
  } as any)
const ConnectedTableSchemaTableNameRouteRoute =
  ConnectedTableSchemaTableNameRouteRouteImport.update({
    id: '/table/$schema/$tableName',
    path: '/table/$schema/$tableName',
    getParentRoute: () => ConnectedRouteRoute,
  } as any)
const ConnectedTableSchemaTableNameIndexRoute =
  ConnectedTableSchemaTableNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnectedTableSchemaTableNameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/settings': typeof SettingsRoute
  '/activity': typeof ConnectedActivityRoute
  '/query': typeof ConnectedQueryRoute
  '/visual-query': typeof ConnectedVisualQueryRoute
  '/er-diagram/$schema': typeof ConnectedErDiagramSchemaRoute
  '/table/$schema/$tableName': typeof ConnectedTableSchemaTableNameRouteRouteWithChildren
  '/table/$schema/$tableName/': typeof ConnectedTableSchemaTableNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/settings': typeof SettingsRoute
  '/activity': typeof ConnectedActivityRoute
  '/query': typeof ConnectedQueryRoute
  '/visual-query': typeof ConnectedVisualQueryRoute
  '/er-diagram/$schema': typeof ConnectedErDiagramSchemaRoute
  '/table/$schema/$tableName': typeof ConnectedTableSchemaTableNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_connected': typeof ConnectedRouteRouteWithChildren
  '/connections': typeof ConnectionsRoute
  '/settings': typeof SettingsRoute
  '/_connected/activity': typeof ConnectedActivityRoute
  '/_connected/query': typeof ConnectedQueryRoute
  '/_connected/visual-query': typeof ConnectedVisualQueryRoute
  '/_connected/er-diagram/$schema': typeof ConnectedErDiagramSchemaRoute
  '/_connected/table/$schema/$tableName': typeof ConnectedTableSchemaTableNameRouteRouteWithChildren
  '/_connected/table/$schema/$tableName/': typeof ConnectedTableSchemaTableNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/settings'
    | '/activity'
    | '/query'
    | '/visual-query'
    | '/er-diagram/$schema'
    | '/table/$schema/$tableName'
    | '/table/$schema/$tableName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/settings'
    | '/activity'
    | '/query'
    | '/visual-query'
    | '/er-diagram/$schema'
    | '/table/$schema/$tableName'
  id:
    | '__root__'
    | '/'
    | '/_connected'
    | '/connections'
    | '/settings'
    | '/_connected/activity'
    | '/_connected/query'
    | '/_connected/visual-query'
    | '/_connected/er-diagram/$schema'
    | '/_connected/table/$schema/$tableName'
    | '/_connected/table/$schema/$tableName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectedRouteRoute: typeof ConnectedRouteRouteWithChildren
  ConnectionsRoute: typeof ConnectionsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_connected': {
      id: '/_connected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ConnectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_connected/visual-query': {
      id: '/_connected/visual-query'
      path: '/visual-query'
      fullPath: '/visual-query'
      preLoaderRoute: typeof ConnectedVisualQueryRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/_connected/query': {
      id: '/_connected/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof ConnectedQueryRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/_connected/activity': {
      id: '/_connected/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ConnectedActivityRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/_connected/er-diagram/$schema': {
      id: '/_connected/er-diagram/$schema'
      path: '/er-diagram/$schema'
      fullPath: '/er-diagram/$schema'
      preLoaderRoute: typeof ConnectedErDiagramSchemaRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/_connected/table/$schema/$tableName': {
      id: '/_connected/table/$schema/$tableName'
      path: '/table/$schema/$tableName'
      fullPath: '/table/$schema/$tableName'
      preLoaderRoute: typeof ConnectedTableSchemaTableNameRouteRouteImport
      parentRoute: typeof ConnectedRouteRoute
    }
    '/_connected/table/$schema/$tableName/': {
      id: '/_connected/table/$schema/$tableName/'
      path: '/'
      fullPath: '/table/$schema/$tableName/'
      preLoaderRoute: typeof ConnectedTableSchemaTableNameIndexRouteImport
      parentRoute: typeof ConnectedTableSchemaTableNameRouteRoute
    }
  }
}

interface ConnectedTableSchemaTableNameRouteRouteChildren {
  ConnectedTableSchemaTableNameIndexRoute: typeof ConnectedTableSchemaTableNameIndexRoute
}

const ConnectedTableSchemaTableNameRouteRouteChildren: ConnectedTableSchemaTableNameRouteRouteChildren =
  {
    ConnectedTableSchemaTableNameIndexRoute:
      ConnectedTableSchemaTableNameIndexRoute,
  }

const ConnectedTableSchemaTableNameRouteRouteWithChildren =
  ConnectedTableSchemaTableNameRouteRoute._addFileChildren(
    ConnectedTableSchemaTableNameRouteRouteChildren,
  )

interface ConnectedRouteRouteChildren {
  ConnectedActivityRoute: typeof ConnectedActivityRoute
  ConnectedQueryRoute: typeof ConnectedQueryRoute
  ConnectedVisualQueryRoute: typeof ConnectedVisualQueryRoute
  ConnectedErDiagramSchemaRoute: typeof ConnectedErDiagramSchemaRoute
  ConnectedTableSchemaTableNameRouteRoute: typeof ConnectedTableSchemaTableNameRouteRouteWithChildren
}

const ConnectedRouteRouteChildren: ConnectedRouteRouteChildren = {
  ConnectedActivityRoute: ConnectedActivityRoute,
  ConnectedQueryRoute: ConnectedQueryRoute,
  ConnectedVisualQueryRoute: ConnectedVisualQueryRoute,
  ConnectedErDiagramSchemaRoute: ConnectedErDiagramSchemaRoute,
  ConnectedTableSchemaTableNameRouteRoute:
    ConnectedTableSchemaTableNameRouteRouteWithChildren,
}

const ConnectedRouteRouteWithChildren = ConnectedRouteRoute._addFileChildren(
  ConnectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectedRouteRoute: ConnectedRouteRouteWithChildren,
  ConnectionsRoute: ConnectionsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
