/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectionsNewRouteImport } from './routes/connections.new'
import { Route as ConnectionsProfileIdEditRouteImport } from './routes/connections.$profileId.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsNewRoute = ConnectionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ConnectionsRoute,
} as any)
const ConnectionsProfileIdEditRoute =
  ConnectionsProfileIdEditRouteImport.update({
    id: '/$profileId/edit',
    path: '/$profileId/edit',
    getParentRoute: () => ConnectionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/connections/new': typeof ConnectionsNewRoute
  '/connections/$profileId/edit': typeof ConnectionsProfileIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/connections/new': typeof ConnectionsNewRoute
  '/connections/$profileId/edit': typeof ConnectionsProfileIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/connections/new': typeof ConnectionsNewRoute
  '/connections/$profileId/edit': typeof ConnectionsProfileIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/settings'
    | '/connections/new'
    | '/connections/$profileId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/settings'
    | '/connections/new'
    | '/connections/$profileId/edit'
  id:
    | '__root__'
    | '/'
    | '/connections'
    | '/settings'
    | '/connections/new'
    | '/connections/$profileId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsRoute: typeof ConnectionsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/new': {
      id: '/connections/new'
      path: '/new'
      fullPath: '/connections/new'
      preLoaderRoute: typeof ConnectionsNewRouteImport
      parentRoute: typeof ConnectionsRoute
    }
    '/connections/$profileId/edit': {
      id: '/connections/$profileId/edit'
      path: '/$profileId/edit'
      fullPath: '/connections/$profileId/edit'
      preLoaderRoute: typeof ConnectionsProfileIdEditRouteImport
      parentRoute: typeof ConnectionsRoute
    }
  }
}

interface ConnectionsRouteChildren {
  ConnectionsNewRoute: typeof ConnectionsNewRoute
  ConnectionsProfileIdEditRoute: typeof ConnectionsProfileIdEditRoute
}

const ConnectionsRouteChildren: ConnectionsRouteChildren = {
  ConnectionsNewRoute: ConnectionsNewRoute,
  ConnectionsProfileIdEditRoute: ConnectionsProfileIdEditRoute,
}

const ConnectionsRouteWithChildren = ConnectionsRoute._addFileChildren(
  ConnectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
